# Generated by Django 4.1.6 on 2023-03-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("bannerimage1", models.ImageField(upload_to="media")),
                ("bannerimage2", models.ImageField(upload_to="media")),
                ("bannerimage3", models.ImageField(upload_to="media")),
                ("bannerimage4", models.ImageField(upload_to="media")),
                ("bannerimage5", models.ImageField(upload_to="media")),
                ("bannerimage6", models.ImageField(upload_to="media")),
            ],
        ),
    ]
